version: '3.8'

services:

  redis-main-1:
    build:
      dockerfile: Dockerfile
    environment:
      REDIS_STACK_DATABASE_PORT: 7001
      REDIS_ARGS: >
        --port 7001
        --bind 0.0.0.0
        --cluster-config-file nodes.conf
        --cluster-enabled yes
        --cluster-node-timeout 5000
        --appendonly yes
        --protected-mode no
    ports:
      - "7001:7001"
      - "8001:8001"

  redis-main-2:
    build:
      dockerfile: Dockerfile
    environment:
      REDIS_ARGS: >
        --port 7002
        --bind 0.0.0.0
        --cluster-config-file nodes.conf
        --cluster-enabled yes
        --cluster-node-timeout 5000
        --appendonly yes
        --protected-mode no
    ports:
      - "7002:7002"

  redis-main-3:
    build:
      dockerfile: Dockerfile
    environment:
      REDIS_ARGS: >
        --port 7003
        --bind 0.0.0.0
        --cluster-config-file nodes.conf
        --cluster-enabled yes
        --cluster-node-timeout 5000
        --appendonly yes
        --protected-mode no
    ports:
      - "7003:7003"

  redis-replica-1:
    build:
      dockerfile: Dockerfile
    environment:
      REDIS_ARGS: >
        --port 7004
        --bind 0.0.0.0
        --cluster-config-file nodes.conf
        --cluster-enabled yes
        --cluster-node-timeout 5000
        --appendonly yes
        --protected-mode no
    ports:
      - "7004:7004"

  redis-replica-2:
    build:
      dockerfile: Dockerfile
    environment:
      REDIS_ARGS: >
        --port 7005
        --bind 0.0.0.0
        --cluster-config-file nodes.conf
        --cluster-enabled yes
        --cluster-node-timeout 5000
        --appendonly yes
        --protected-mode no
    ports:
      - "7005:7005"

  redis-replica-3:
    build:
      dockerfile: Dockerfile
    environment:
      REDIS_ARGS: >
        --port 7006
        --bind 0.0.0.0
        --cluster-config-file nodes.conf
        --cluster-enabled yes
        --cluster-node-timeout 5000
        --appendonly yes
        --protected-mode no
    ports:
      - "7006:7006"

  redis-cluster-create:
    build:
      dockerfile: Dockerfile
    depends_on:
      - redis-main-1
      - redis-main-2
      - redis-main-3
      - redis-replica-1
      - redis-replica-2
      - redis-replica-3
    command: [
        "/bin/bash", "-c",
        "echo yes | redis-cli --cluster-replicas 1 --cluster create redis-main-1:7001 redis-main-2:7002 redis-main-3:7003 redis-replica-1:7004 redis-replica-2:7005 redis-replica-3:7006"
    ]

  redis-commander:
    image: rediscommander/redis-commander
    depends_on:
      - redis-cluster-create
    environment:
      REDIS_HOSTS: local:redis-main-1:7001,local:redis-main-2:7002,local:redis-main-3:7003,local:redis-replica-1:7004,local:redis-replica-2:7005,local:redis-replica-3:7006
      STANDALONE: "true"
    ports:
      - "8085:8081"
