version: '3.8'

services:
  redis-main-1:
    image: redis/redis-stack-server:7.2.0-v6
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7001" ]
    ports:
      - "7001:7001"

  redis-main-2:
    image: redis/redis-stack-server:7.2.0-v6
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7002" ]
    ports:
      - "7002:7002"

  redis-main-3:
    image: redis/redis-stack-server:7.2.0-v6
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7003" ]
    ports:
      - "7003:7003"

  redis-replica-1:
    image: redis/redis-stack-server:7.2.0-v6
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7004" ]
    ports:
      - "7004:7004"

  redis-replica-2:
    image: redis/redis-stack-server:7.2.0-v6
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7005" ]
    ports:
      - "7005:7005"

  redis-replica-3:
    image: redis/redis-stack-server:7.2.0-v6
    volumes:
      - ./resources/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port", "7006" ]
    ports:
      - "7006:7006"

  redis-cluster-create:
    image: redis/redis-stack-server:7.2.0-v6
    depends_on:
      - redis-main-1
      - redis-main-2
      - redis-main-3
      - redis-replica-1
      - redis-replica-2
      - redis-replica-3
    command: [
        "/bin/bash", "-c",
        "echo yes | redis-cli --cluster-replicas 1 --cluster create redis-main-1:7001 redis-main-2:7002 redis-main-3:7003 redis-replica-1:7004 redis-replica-2:7005 redis-replica-3:7006"
    ]

  redis-commander:
    image: rediscommander/redis-commander
    depends_on:
      - redis-cluster-create
    environment:
      REDIS_HOSTS: local:redis-main-1:7001,local:redis-main-2:7002,local:redis-main-3:7003,local:redis-replica-1:7004,local:redis-replica-2:7005,local:redis-replica-3:7006
      STANDALONE: "true"
    ports:
      - "8085:8081"

  redisinsight-config:
    image: ellerbrock/alpine-bash-curl-ssl
    entrypoint: [ ]
    command: [
        "/bin/bash", "-c",
        "sleep 20 &&\
        curl --location --request POST 'redisinsight:8001/api/instance/' \
        --header 'Content-Type: application/json' \
                                  --data-raw '{
          \"name\": \"CLUSTER-LOCAL\",
          \"connectionType\": \"CLUSTER\",
          \"seedNodes\": [
            {
              \"host\": \"redis-main-1\",
              \"port\": 7001
            }
          ]
        }'"
    ]

  redisinsight:
    image: redislabs/redisinsight
    depends_on:
      - redis-cluster-create
      - redisinsight-config
    ports:
      - "8083:8001"